In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [6]:
store = pd.read_excel(r"C:\Users\polin\Desktop\GenAI_AgenticAI_Prac\Python Prac\19th_PandasPrac\Superstore_Orders_Supplies.xlsx")

In [7]:
store

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,ORD-0001,Mon May 20 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Laptop,Technology,East,Illinois,1,850.0,0.05,104.25
1,ORD-0002,Mon Oct 14 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Keyboard,Technology,South,Texas,1,45.0,0.05,10.15
2,ORD-0003,Wed May 22 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Monitor,Technology,East,California,6,1650.0,0.05,199.65
3,ORD-0004,Tue Oct 01 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Office Chair,Furniture,East,Illinois,8,1000.0,0.00,294.09
4,ORD-0005,Sat Feb 10 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Notebook,Office Supplies,Central,Florida,5,42.5,0.05,10.93
...,...,...,...,...,...,...,...,...,...,...,...
395,ORD-0396,Sat Jul 06 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Desk,Furniture,South,Texas,9,2700.0,0.15,183.96
396,ORD-0397,Sun Apr 07 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Bookshelf,Furniture,West,Illinois,7,1260.0,0.20,232.15
397,ORD-0398,Tue Jan 23 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Bookshelf,Furniture,West,California,2,360.0,0.05,40.80
398,ORD-0399,Fri Nov 15 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Paper,Office Supplies,West,Illinois,9,54.0,0.20,5.89
399,ORD-0400,Wed Jul 03 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Paper,Office Supplies,Central,California,1,6.0,0.20,1.17

In [8]:
id(store)

2261584764544

In [9]:
len(store)

400

In [10]:
store.shape

(400, 11)

In [11]:
store.columns

Index(['Order ID', 'Order Date', 'Customer Name', 'Product Name', 'Category',
       'Region', 'State', 'Quantity', 'Sales', 'Discount', 'Profit'],
      dtype='object')

In [12]:
len(store.columns)

11

In [13]:
store.isnull()

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
395,False,False,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False,False,False
398,False,False,False,False,False,False,False,False,False,False,False
399,False,False,False,False,False,False,False,False,False,False,False

In [14]:
store.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Product Name     0
Category         0
Region           0
State            0
Quantity         0
Sales            0
Discount         0
Profit           0
dtype: int64

In [15]:
store[:]

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,ORD-0001,Mon May 20 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Laptop,Technology,East,Illinois,1,850.0,0.05,104.25
1,ORD-0002,Mon Oct 14 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Keyboard,Technology,South,Texas,1,45.0,0.05,10.15
2,ORD-0003,Wed May 22 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Monitor,Technology,East,California,6,1650.0,0.05,199.65
3,ORD-0004,Tue Oct 01 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Office Chair,Furniture,East,Illinois,8,1000.0,0.00,294.09
4,ORD-0005,Sat Feb 10 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Notebook,Office Supplies,Central,Florida,5,42.5,0.05,10.93
...,...,...,...,...,...,...,...,...,...,...,...
395,ORD-0396,Sat Jul 06 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Desk,Furniture,South,Texas,9,2700.0,0.15,183.96
396,ORD-0397,Sun Apr 07 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Bookshelf,Furniture,West,Illinois,7,1260.0,0.20,232.15
397,ORD-0398,Tue Jan 23 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Bookshelf,Furniture,West,California,2,360.0,0.05,40.80
398,ORD-0399,Fri Nov 15 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Paper,Office Supplies,West,Illinois,9,54.0,0.20,5.89
399,ORD-0400,Wed Jul 03 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Paper,Office Supplies,Central,California,1,6.0,0.20,1.17

In [16]:
store[0:10]

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,ORD-0001,Mon May 20 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Laptop,Technology,East,Illinois,1,850.0,0.05,104.25
1,ORD-0002,Mon Oct 14 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Keyboard,Technology,South,Texas,1,45.0,0.05,10.15
2,ORD-0003,Wed May 22 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Monitor,Technology,East,California,6,1650.0,0.05,199.65
3,ORD-0004,Tue Oct 01 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Office Chair,Furniture,East,Illinois,8,1000.0,0.00,294.09
4,ORD-0005,Sat Feb 10 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Notebook,Office Supplies,Central,Florida,5,42.5,0.05,10.93
5,ORD-0006,Thu Nov 21 2024 05:30:00 GMT+0530 (India Stand...,Mary Johnson,Laptop,Technology,West,Florida,10,8500.0,0.05,1594.90
6,ORD-0007,Sat Apr 27 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Stapler,Office Supplies,Central,California,1,12.0,0.00,3.09
7,ORD-0008,Wed May 15 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Paper,Office Supplies,Central,Illinois,3,18.0,0.05,2.30
8,ORD-0009,Thu Jan 25 2024 05:30:00 GMT+0530 (India Stand...,Mary Johnson,Paper,Office Supplies,South,Illinois,2,12.0,0.00,1.36
9,ORD-0010,Sat Jan 06 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Desk,Furniture,Central,New York,9,2700.0,0.00,620.94

In [17]:
store[0:20:5]

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,ORD-0001,Mon May 20 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Laptop,Technology,East,Illinois,1,850.0,0.05,104.25
5,ORD-0006,Thu Nov 21 2024 05:30:00 GMT+0530 (India Stand...,Mary Johnson,Laptop,Technology,West,Florida,10,8500.0,0.05,1594.90
10,ORD-0011,Mon Apr 01 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Desk,Furniture,West,Texas,9,2700.0,0.20,606.48
15,ORD-0016,Thu Oct 03 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Paper,Office Supplies,South,Texas,4,24.0,0.05,5.45

In [18]:
store.head()

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,ORD-0001,Mon May 20 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Laptop,Technology,East,Illinois,1,850.0,0.05,104.25
1,ORD-0002,Mon Oct 14 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Keyboard,Technology,South,Texas,1,45.0,0.05,10.15
2,ORD-0003,Wed May 22 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Monitor,Technology,East,California,6,1650.0,0.05,199.65
3,ORD-0004,Tue Oct 01 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Office Chair,Furniture,East,Illinois,8,1000.0,0.00,294.09
4,ORD-0005,Sat Feb 10 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Notebook,Office Supplies,Central,Florida,5,42.5,0.05,10.93

In [19]:
store.head(3)

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,ORD-0001,Mon May 20 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Laptop,Technology,East,Illinois,1,850.0,0.05,104.25
1,ORD-0002,Mon Oct 14 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Keyboard,Technology,South,Texas,1,45.0,0.05,10.15
2,ORD-0003,Wed May 22 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Monitor,Technology,East,California,6,1650.0,0.05,199.65

In [20]:
store.tail()

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
395,ORD-0396,Sat Jul 06 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Desk,Furniture,South,Texas,9,2700.0,0.15,183.96
396,ORD-0397,Sun Apr 07 2024 05:30:00 GMT+0530 (India Stand...,James Wilson,Bookshelf,Furniture,West,Illinois,7,1260.0,0.20,232.15
397,ORD-0398,Tue Jan 23 2024 05:30:00 GMT+0530 (India Stand...,John Smith,Bookshelf,Furniture,West,California,2,360.0,0.05,40.80
398,ORD-0399,Fri Nov 15 2024 05:30:00 GMT+0530 (India Stand...,Robert Brown,Paper,Office Supplies,West,Illinois,9,54.0,0.20,5.89
399,ORD-0400,Wed Jul 03 2024 05:30:00 GMT+0530 (India Stand...,Linda Davis,Paper,Office Supplies,Central,California,1,6.0,0.20,1.17

In [21]:
store.isna()

,Order ID,Order Date,Customer Name,Product Name,Category,Region,State,Quantity,Sales,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
395,False,False,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False,False,False
398,False,False,False,False,False,False,False,False,False,False,False
399,False,False,False,False,False,False,False,False,False,False,False

In [22]:
store.describe()

         Quantity        Sales    Discount       Profit
count  400.000000   400.000000  400.000000   400.000000
mean     5.652500  1298.382500    0.104125   214.357925
std      2.870949  1881.413271    0.070368   332.705005
min      1.000000     6.000000    0.000000     1.070000
25%      3.000000    72.000000    0.050000    11.897500
50%      6.000000   520.000000    0.100000    86.395000
75%      8.000000  1760.000000    0.150000   289.417500
max     10.000000  8500.000000    0.200000  2065.640000